name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag express-hello-world:${{ github.sha }} --tag express-hello-world:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push the Docker image
      run: |
        docker tag express-hello-world:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/test-trustpoint:${{ github.sha }}
        docker tag express-hello-world:latest ${{ secrets.DOCKER_HUB_USERNAME }}/test-trustpoint:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/test-trustpoint:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/test-trustpoint:latest
